### ISSUE TITLE
Feature: Event Notification

### ISSUE THREAD

**Issue by Shourya742** [Bitshala/discord-bot#3]
Finalize the Event Notification Process. It should incorporate Raj's instructions about the content. Presently, the server hosts two recurring events: 

1. Optech Sunday
2. Reading Club

**Comment by basantagoswami** [comment]
I am taking this up.

**Comment by Shourya742** [comment]
@basantagoswami assigned

**Comment by basantagoswami** [comment]
@Shourya742 can you close his as done.
